### PR TITLE
Create topological_sort.py

### PR DESCRIPTION
**Pull request by Mohitkumar6122**
```
# Description
You are given a directed graph with n vertices and m edges. You have to number the vertices so that every edge leads from the vertex with a smaller number assigned to the vertex with a larger one.

In other words, you want to find a permutation of the vertices (topological order) which corresponds to the order defined by all edges of the graph. 
it is done through Topological sorting which is quite popular and frequently asked in interviews.

Make sure you have:

- [x] Visited http://join.codezoned.com/
- [x] Starred ScriptsDump!
- [ ] Referred the issue number in the fixes title below.
- [x] Made a PR in Join_codezoned.
- [x] Joined our discord server.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [x] New Script
- [x] New Category (Is any new category being made to accommodate this script)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
```

### CODE REVIEW

**Comment by Mohitkumar6122** [comment]
@master-fury could you review my PR ?

**Review by master-fury — CHANGES_REQUESTED** [review]
Please add a description to your scripts (add on the top of the file), so that people can learn from your work

**Comment by Mohitkumar6122** [comment]
> Please add a description to your scripts (add on the top of the file), so that people can learn from your work

@master-fury  please have a look .

**Review by master-fury — APPROVED** [review]
Nice work!✌

**Pull request merged**
