### PR TITLE
Added Hierarchical Clustering and Median Filtering

### LINKED ISSUE #57: Add more Machine learning scripts! #Hacktoberfest
Machine learning sector has been mostly untouched by the community. Add em!

### PR DESCRIPTION
**Pull request by rudrajit1729**
```
# Description

Added Hierarchical Clustering to the ML folder along with example dendogram and result on a small dataset attached for example.
Added Median Filtering Technique in C along with metric calculation such as Root Mean Squared Error(RMSE), Peak Signal to Noise Ratio(PSNR), Image Enhancement Factor(IEF), Structural Similarity(SSIM) and time for computation. Median Filtering is specifically the standard method for removal  of Salt and Pepper Noise.

Fixes #57 
Also Added script to Image Processing Folder

## Type of change


- [ ] New Script
- [ ] New feature (non-breaking change which adds functionality)
```

### CODE REVIEW

**Comment by rudrajit1729** [comment]
Please review and suggest changes (if any). Else please merge the added scripts. Thanks. @ionicc

**Comment by rudrajit1729** [comment]
Please review and suggest changes (if any). Else please merge the added scripts. Thanks. @ionicc @master-fury

**Review by master-fury — CHANGES_REQUESTED** [review]
Nice work! Can you please write a detailed readme so that many people can use your code to understand the concept?

**Comment by rudrajit1729** [comment]
Sure.

**Comment by rudrajit1729** [comment]
@master-fury I have added detail readme files explaining the concept for both the algorithms - Hierarchical Clustering and Median Filtering. I have also mentioned the scope and the utilities of the algorithms. Please review and suggest changes (if any).

**Comment by rudrajit1729** [comment]
@master-fury I have added detailed readme files explaining the concepts for both the algorithms - Hierarchical Clustering and Median Filtering. I have also mentioned the scope and the utilities of the algorithms. Please review and suggest changes (if any).

**Review by master-fury — APPROVED** [review]
Awesome work!✌👍 Add more scripts! Don't forget to ⭐ us.

**Pull request merged**
