### PR TITLE
Added Machine Learning model to predict anime according to rating and name

### PR DESCRIPTION
**Pull request by Mohitkumar6122**
```
# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. Include a proper title of the Script that is being entered.

Make sure you have:

- [✔] Visited http://join.codezoned.com/
- [✔] Starred ScriptsDump!
- [ ] Referred the issue number in the fixes title below.
- [✔] Made a PR in Join_codezoned.
- [✔] Joined our discord server.

**Uploaded New Project**

## Type of change

Please delete options that are not relevant.

- [✔] New Script
- [✔] New Category (Is any new category being made to accommodate this script)

```

### CODE REVIEW

**Review by Aniket-Mishra — CHANGES_REQUESTED** [review]
rating.csv is missing.
While getting recommendations of anime names, it's throwing a Key Error for user_id.
key_error
 
Cheers,
Aniket

**Comment by Mohitkumar6122** [comment]
> rating.csv is missing.
> While getting recommendations of anime names, it's throwing a Key Error for user_id.
> key_error
> 
> Cheers,
> Aniket

I am still looking into this matter ... but this error does't occur in my computer.. but still trying to figure it out .

**Comment by Mohitkumar6122** [comment]
I could't figure out what is problem so i am creating a new model using the nearest neighbor approach. it is also  working  well.

**Comment by Mohitkumar6122** [comment]
@master-fury could you please review this PR ?

**Review by Aniket-Mishra — APPROVED** [review]

**Comment by Aniket-Mishra** [comment]
Looks good!

**Pull request closed without merging**
