### PR TITLE
Add Go implementation of Cycle Sort

### PR DESCRIPTION
**Pull request by xfjdfkj**

### CODE REVIEW

**Comment by master-fury** [comment]
Fill the PR template.

**Review by Aniket-Mishra — CHANGES_REQUESTED** [review]
You have to fill the PR template for this repo. Please check it out in the README and do the same. Thank you!

**Comment by hrishikeshcs** [comment]
The PR template has been filled.

**Comment by master-fury** [comment]
> The PR template has been filled.

No mate, Please add a description and the things you have completed in that checklist, I cant see description there.

**Pull request closed without merging**
