### PR TITLE
text -> sign using transformer decoder

### LINKED ISSUE #224: Add NLP scripts
It can be Email filters, Smart assistants , Search results, Predictive text, Language translation etc.

### PR DESCRIPTION
**Pull request by gittygupta**
# Description

Contributed a sign language production architecture that converts text to german sign language using rwth-phoenix-2014t dataset, to NLP folder under Machine Learning

Make sure you have:

- [x] Visited http://join.codezoned.com/
- [x] Starred ScriptsDump!
- [x] Referred the issue number in the fixes title below.
- [ ] Made a PR in Join_codezoned.
- [ ] Joined our discord server.

Fixes #224 

## Added a folder containing all the scripts

Please delete options that are not relevant.

- [x] New Script
- [ ] New Category (Is any new category being made to accommodate this script)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)

### CODE REVIEW

**Review by master-fury — CHANGES_REQUESTED** [review]
Nice work! Can you please write a proper readme for the users so that your code can be used by people also it will help people understand the concept better? Also select the things you did while raising the PR (follow the template) like star, new script etc.

**Comment by gittygupta** [comment]
> Nice work! Can you please write a proper readme for the users so that your code can be used by people also it will help people understand the concept better? Also select the things you did while raising the PR (follow the template) like star, new script etc.

Yes I just ticked those options, and would it help if I uploaded a pdf of the mathematics behind this whole thing? Because writing a whole markdown file will be a bit time consuming, but I have a whole proposal written for it.

**Comment by gittygupta** [comment]
> > Nice work! Can you please write a proper readme for the users so that your code can be used by people also it will help people understand the concept better? Also select the things you did while raising the PR (follow the template) like star, new script etc.
> 
> Yes I just ticked those options, and would it help if I uploaded a pdf of the mathematics behind this whole thing? Because writing a whole markdown file will be a bit time consuming, but I have a whole proposal written for it.

Though I have added the pdf, please let me know if a markdown readme file would be so necessary. I will surely do it. Also, the pdf will definitely help the readers. Please do consider merging if you feel it is contributory. Thank you!

**Comment by master-fury** [comment]
> > Nice work! Can you please write a proper readme for the users so that your code can be used by people also it will help people understand the concept better? Also select the things you did while raising the PR (follow the template) like star, new script etc.
> 
> Yes I just ticked those options, and would it help if I uploaded a pdf of the mathematics behind this whole thing? Because writing a whole markdown file will be a bit time consuming, but I have a whole proposal written for it.

Sure, that will do it.

**Review by master-fury — APPROVED** [review]
Nice work!

**Comment by gittygupta** [comment]
> Nice work!

Thank you! Its my pleasure.

**Pull request merged**
