### PR TITLE
Added Array searching, sorting, and Data Structure scripts and included badges in Readme.md

### PR DESCRIPTION
**Pull request by Sheetal777**
```
# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. Include a proper title of the Script that is being entered.

- I updated few codes in Data Structures folder and added badges in Readme.md files as enhancement.

Script 1: [oddEvenSort.py] A python program to implement odd-even sorting or Brick Sort. It is a kind of bubble sort since it is divided into two phases, i.e. odd phase & even phase and bubble sort is implemented on each of the phases.

Script 2: [linear_search_recursion.py] Another python program to search an element linearly in an array using Recursion (Read again 💯 ) Why recursion? Because it makes the task easier and reduces time complexity.

Script 3: [circular_linked_list.py] Another python program to implement and Insert a node by taking an pointer pointing to locations one want to insert a node to. The insertion operations are carried out: 
a. in empty linked list
b. at beginning of the linked  list
c. at end of the linked list
d. in between the nodes

Make sure you have:

- [ ] Visited http://join.codezoned.com/
- [ ] Starred ScriptsDump!
- [ ] Referred the issue number in the fixes title below.
- [ ] Made a PR in Join_codezoned.

Fixes # (issue)

## Type of change 

1. Added Array Sorting script.
2. Added Array Searching script. 
3. Data Structures - Circular Linked List script.
4. Enhancement of Readme file with a Badge.

- [ ] New Script
- [ ] New feature (non-breaking change which adds functionality)
```

### CODE REVIEW

**Comment by Sheetal777** [comment]
Hello there, I just added few python scripts in your repository which were great add-on(s) to the existing scripts. Also, I added an interesting badge in the Readme as an enhancement. Kindly check these out and considering merging my pull request. Would love to contribute more 👍

**Review by master-fury — CHANGES_REQUESTED** [review]
Nice work! Can you please include a description of what these scripts do. Btw name is obvious but for beginners it will be great headstart.

**Comment by Sheetal777** [comment]
Yes, for sure. Doing it right away!

**Comment by Sheetal777** [comment]
Hey! I updated the description. Kindly review and inform about any other changes (if there). Thanks 👍

**Review by master-fury — CHANGES_REQUESTED** [review]
Awesome work! just copy the description what you wrote in PR into your scripts accordingly so that it can be easier to read and understand (add on the top)

**Comment by Sheetal777** [comment]
Hey! Its done. Check it out.

**Review by master-fury — APPROVED** [review]
Awesome work👍✌. Don't forget to star us!

**Comment by Sheetal777** [comment]
Thanks :) For sure!

**Pull request merged**
